### ISSUE TITLE
MongoDBいれる

### ISSUE THREAD

**Issue by 75asa** [75asa/time-liner#25]
# なんでやるの？
- 自分の分報に投稿されたチャンネル 🆔 とts（タイムスタンプ）をTLに投稿したタイムスタンプと紐付けて保存するように

# 完了条件
- Heroku に MongoDB が入って TL警察とつながってること
- TypeORM が使えるようになること

**Comment by 75asa** [comment]
TypeORM, Mongoose ?

**Comment by 75asa** [comment]
https://scrapbox.io/kadoyau/TypeScript%E3%81%A7mongoose%E3%82%92%E4%BD%BF%E3%81%86
https://qiita.com/tejitak/items/b6965380afd600db6513

**Comment by 75asa** [comment]
TypeORMにする（今後のDB自体の移植性を考慮して）

**Comment by 75asa** [comment]
@tk-ozawa https://api.slack.com/lang/ja-jp/hello-world-bolt

**Comment by tk-ozawa** [comment]
@75asa データベースのテーブルどうしましょ
とりあえず、
- チャンネルのID
- チャンネル内の投稿ID
- タイムスタンプ
辺りで投稿テーブルを作るべきですかね？

**Comment by 75asa** [comment]
@tk-ozawa んー、どうしよっかね
DBいれてやりたいことベースで考えるとスタンプコレクションとかあったほうがいいかな？
あと edited 項目と edit したときの ts とか？

**Comment by 75asa** [comment]
あとはスタンプ押した　ユーザ🆔をいれるコレクションと
スレッドでだれがメッセージをおくったか

**Comment by 75asa** [comment]
投稿者、投稿先のチャンネル名、チャンネル🆔

**Comment by 75asa** [comment]
@sizukutamago このへんどう思います？(雑になげる)

**Comment by 75asa** [comment]
ER作ります
