### ISSUE TITLE
Actions 入れる

### ISSUE THREAD

**Issue by 75asa** [75asa/time-liner#48]
Lint だけでも

**Comment by 75asa** [comment]
@taichi0514 emoji-syncher のついでにこっちもお願いできますと //

**Comment by taichi0514** [comment]
無料のプランだったらaction成功しないとPRmergeできないけどそれでもよい？

**Comment by taichi0514** [comment]
action成功しないとPRmergeできません。
↑無料のプランだったら設定できないけどそれでもよい？
あんまり意味ないかなと思った

**Comment by 75asa** [comment]
> action成功しないとPRmergeできません。
> ↑無料のプランだったら設定できないけどそれでもよい？
> あんまり意味ないかなと思った

@taichi0514 え？そうなの？公開リポやけどむりなんや🤔

**Comment by usagizmo** [comment]
@75asa
このあたりの設定？（別リポジトリ）
![CleanShot 2020-12-02 at 08 40 32@2x](https://user-images.githubusercontent.com/1271863/100809721-223cda80-347a-11eb-9dff-3ddbddc6df92.png)

**Comment by 75asa** [comment]
@usagizmo @taichi0514 ここかな？
チェックすればいいの？
![Uploading image.png…]()

**Comment by usagizmo** [comment]
どうかな！

**Comment by 75asa** [comment]
しました！
@taichi0514 これで Action いれたらいけるとおもいます

**Comment by taichi0514** [comment]
それです！
action追加したらそこに出てくるようになる！

**Comment by taichi0514** [comment]
↑
https://github.com/75asa/time-liner/pull/66
