### ISSUE TITLE
マイグレーションしたいよね

### ISSUE THREAD

**Issue by tk-ozawa** [75asa/time-liner#62]
# なぜやるか？
- 動作確認のとき予めデータベースをローカルに作成しないといけないから
- 現状、そうしないとDB接続系の確認ができないから
- 単体テスト時のモックとしてもマイグレーションしたい
  - e.g. Laravel, Rails の seed コマンド
  - [How to seed TypeORM](https://medium.com/@bansalsushil_34403/how-to-seed-typeorm-d9637a5948cc)

# 受け入れ条件
- マイグレーションの実装タスクができること

# 備考
- このタスクでは調査だけに留める

## 資料
- [Typeorm でマイグレーションをしよう](https://qiita.com/qualitia_cdev/items/eb8f2c614c0435b9a120)
- [typeORM Migrations](https://typeorm.io/#/migrations)
- [typeorm:migration create on New Project Does Not Recognize Entities - “No changes in database schema were found - cannot generate a migration.”](https://stackoverflow.com/questions/63759112/typeormmigration-create-on-new-project-does-not-recognize-entities-no-change)
  - typeorm では entity から自動で migration file を生成してくれるけど、RDB しかサポートしてないみたい
  - NoSQL なら schema ないし必要なくない？ってスタンス
  - ただ collection, document の全体的な schema が欲しかったり、変更履歴などの Log が欲しい場合は [migrate-mongo](https://www.npmjs.com/package/migrate-mongo) を使ったら？とのこと
    - 別の コラムでも migrate-mongo を推奨してる
    - [All you need to know about MongoDB schema migrations in node.js](https://softwareontheroad.com/database-migration-node-mongo/)
      - ただ、これなら、 typeorm で生のクエリ書けばいいだけ、 typeorm でも migration file 自体は生成される
      - ただし、 ***Entity からの自動生成は対応してない***
- [TypeORMはNode.js開発のスタンダードになるか？](https://qiita.com/tejitak/items/b6965380afd600db6513)
- [Recommended way of executing MongoDB migrations #5187](https://github.com/typeorm/typeorm/issues/5187)
- [How To Use TypeORM with MongoDB?](https://developer.mongodb.com/community/forums/t/how-to-use-typeorm-with-mongodb/8977)

**Comment by 75asa** [comment]
@tk-ozawa 概要アプデしました
今後イシューたてるときはこんな感じにするようにしてほしいです
（まだやってないやつは僕もアプデします）

**Comment by 75asa** [comment]
typeorm 捨てて、 prisma にしたほうがいいかもしれない
https://www.prisma.io/docs/concepts/components/prisma-client/crud#upsert

**Comment by 75asa** [comment]
↑ なので migration というよりも seeds ができるようにしたいのでこのイシューはクローズ
